### ISSUE TITLE
Error when deploy shiny app with sqtlviztool on Rstudio-Connect server

### ISSUE THREAD

**Issue by llgai508** [jackhump/sqtlviztools#1]
When trying to publish shiny app onto Rstudio-connect server, the package cannot be installed automatically by the Rstudio packart. The rstudio support team found there is an issue with the DESCRIPTION for the sqtlviztools package. Towards the end of the file on line 30, there is a blank line. The RStudio Connect produces an error because of this line.
 ...

    grid,

    gtable,

    ggrepel,

    ggbeeswarm

Remotes:

    jackhump/leafviz

Can you please update the DESCRIPTION file to remove this line to facilitate our shiny app publish on rstudio-connect server?

Thanks
Lili

**Comment by jackhump** [comment]
Hi Lili,

pleased to hear that you're making use of the package! I've amended the DESCRIPTION file, let me know if that works.

I'd love to see the app if you're willing to show me.

best wishes,

Jack

**Comment by llgai508** [comment]
Hi Jack,

Thanks a lot for your quick support. The issue is solved. 
It is just your example sqtlviztool app published to our rstudio-connect server by a user.

Thanks,
Lili

**Comment by jackhump** [comment]
Wait, are you Lili from Mount Sinai HPC?

Thank YOU for all your support!

Best,
Jack

On Dec 17, 2020 9:43 AM, llgai508 <notifications@github.com> wrote:

Hi Jack,

Thanks a lot for your quick support. The issue is solved.
It is just your example sqtlviztool app published to our rstudio-connect server by a user.

Thanks,
Lili

**Comment by llgai508** [comment]
Yes. I believe we met before.

**Comment by vegetableneedhelp** [comment]
hi,
i'm not good for codes.
 there is an error when i run the sqltviztools on my computer:
"zless" is not  an internal or external command. 
should i run R on linux??
thanks very much!
